#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
4-render-export.py — Render a Blender VSE project to a final MP4

Renders outside Blender's built-in FFmpeg encoder, which doesn't expose real
CRF/GOP/preset control. Instead: render a lossless, resumable PNG image
sequence via Blender's Python API, mix the VSE's audio down to WAV, then
shell out to ffmpeg to mux the two into the final MP4 with real encoder
control — matching the CRF 18 standard 2-transcode.py already holds the rest
of the pipeline to.

Usage:
    python3 4-render-export.py /path/to/project.blend
    python3 4-render-export.py                          # prompted to drag-and-drop
    python3 4-render-export.py project.blend --handoff   # keyframe interval 1,
                                                         # for captions/AE/Premiere
    python3 4-render-export.py project.blend --dry-run

Dependencies:
    blender — must be on PATH or at the macOS default location
    ffmpeg  — must be on PATH

Platform: macOS primary, Linux Mint compatible.
"""

import argparse
import datetime
import glob
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from fractions import Fraction

# ---------------------------------------------------------------------------
# ANSI color helpers
# ---------------------------------------------------------------------------

USE_COLOR = sys.stdout.isatty()

def _c(code, text):
    return f"\033[{code}m{text}\033[0m" if USE_COLOR else text

def ok(msg):     print(_c("0;32",  f"✔ {msg}"))
def warn(msg):   print(_c("1;33",  f"⚠ {msg}"), file=sys.stderr)
def die(msg):    print(_c("0;31",  f"✖ {msg}"), file=sys.stderr); sys.exit(1)
def say(msg):    print(_c("0;36",  msg))
def header(msg): print(_c("1;36",  f"\n── {msg} ──\n"))


# ---------------------------------------------------------------------------
# Path sanitiser (drag-and-drop / copy-paste safe)
# ---------------------------------------------------------------------------

def sanitize_path(raw: str) -> str:
    p = raw.strip()
    if len(p) >= 2 and p[0] in ('"', "'") and p[-1] == p[0]:
        p = p[1:-1]
    for esc in (" ", "&", "(", ")", "[", "]", "!", "#", "$", "@", ",", ";"):
        p = p.replace(f"\\{esc}", esc)
    return p.strip()


def prompt_for_blend() -> str:
    print()
    print("  Drag-and-drop your .blend file here, or paste/type the path:")
    print("  > ", end="", flush=True)
    return sanitize_path(input())


# ---------------------------------------------------------------------------
# Tool discovery
# ---------------------------------------------------------------------------

BLENDER_HINTS = [
    "/Applications/Blender.app/Contents/MacOS/Blender",   # macOS default
    "/usr/bin/blender",                                   # Linux distro package
    "/usr/local/bin/blender",
    "/snap/bin/blender",
    # Glob patterns. Extracting the official tarball is the normal way to run a
    # current Blender on Linux, since distro packages lag by years — those land
    # at versioned paths a fixed list can never cover.
    os.path.expanduser("~/opt/blender-*/blender"),
    os.path.expanduser("~/blender-*/blender"),
    os.path.expanduser("~/blender/blender"),
    "/opt/blender-*/blender",
    "/usr/local/blender-*/blender",
]

def resolve_hint(hints):
    """
    First hint resolving to an executable, in hint order so priority is kept.

    Entries may be glob patterns — see BLENDER_HINTS. When one pattern matches
    several installs, the highest version number in the path wins, so a machine
    with both blender-3.6 and blender-4.5 unpacked gets 4.5.
    """
    for pattern in hints:
        if not pattern:
            continue
        matches = [p for p in glob.glob(pattern)
                   if os.path.isfile(p) and os.access(p, os.X_OK)]
        if matches:
            return max(matches,
                       key=lambda p: [int(n) for n in re.findall(r"\d+", p)])
    return None


def find_blender() -> str:
    found = shutil.which("blender")
    if not found:
        found = resolve_hint(BLENDER_HINTS)
    if not found:
        die(
            "blender not found on PATH or at common locations.\n"
            "  Install Blender or add it to PATH and try again."
        )
    ok(f"Found blender: {found}")
    return found


def find_tool(name: str, hints: list[str] | None = None) -> str:
    found = shutil.which(name)
    if not found and hints:
        for h in hints:
            if h and os.path.isfile(h) and os.access(h, os.X_OK):
                found = h
                break
    if not found:
        die(f"'{name}' not found. Install it or add it to PATH.\n"
            f"  macOS:  brew install ffmpeg")
    return found


# ---------------------------------------------------------------------------
# Blender Python payload — PNG sequence render + audio mixdown
# ---------------------------------------------------------------------------

RENDER_TEMPLATE = '''\
# AUTO-GENERATED by 4-render-export.py — do not edit by hand
import bpy

BLEND_FILE   = {blend_file!r}
FRAMES_DIR   = {frames_dir!r}
WAV_PATH     = {wav_path!r}
IMAGE_FORMAT  = {image_format!r}
JPEG_QUALITY  = {jpeg_quality!r}
TARGET_HEIGHT = {target_height!r}   # 0 = render at full project resolution

bpy.ops.wm.open_mainfile(filepath=BLEND_FILE)

scene = bpy.context.scene
fps = scene.render.fps / scene.render.fps_base

# ── Resolution. Scale via resolution_percentage, never resolution_x/y:
# 3-import-vse.py fits strips to the scene size, so changing the scene's
# pixel dimensions would re-frame every clip. The percentage scales the
# finished render instead, leaving composition identical.
if TARGET_HEIGHT and TARGET_HEIGHT < scene.render.resolution_y:
    RES_PERCENT = max(1, round(TARGET_HEIGHT / scene.render.resolution_y * 100))
else:
    RES_PERCENT = 100
scene.render.resolution_percentage = RES_PERCENT
out_x = int(scene.render.resolution_x * RES_PERCENT / 100)
out_y = int(scene.render.resolution_y * RES_PERCENT / 100)

print()
print("=" * 60)
print("  RENDER EXPORT")
print("=" * 60)
print(f"  Input       : {{BLEND_FILE}}")
print(f"  Frame range : {{scene.frame_start}} - {{scene.frame_end}}")
print(f"  FPS         : {{fps:.6f}}")
print(f"  Resolution  : {{scene.render.resolution_x}}x{{scene.render.resolution_y}}"
      f" @ {{RES_PERCENT}}% -> {{out_x}}x{{out_y}}")
print(f"  Frames      : {{IMAGE_FORMAT}}")
print("=" * 60)

# ── Image sequence — resumable, with real encoder control happening later in
# ffmpeg rather than Blender's own limited FFmpeg output panel. PNG is
# lossless for a delivery render; --review uses JPEG instead, because a
# review proxy covers the whole uncut timeline and a lossless intermediate
# at that length runs to tens of gigabytes of scratch for no visible gain.
scene.render.image_settings.file_format = IMAGE_FORMAT
scene.render.image_settings.color_mode = 'RGB'
if IMAGE_FORMAT == 'JPEG':
    scene.render.image_settings.quality = JPEG_QUALITY
else:
    scene.render.image_settings.color_depth = '8'
scene.render.use_file_extension = True
# Explicit 5-digit '#' padding — Blender's default padding width varies with
# frame count, and ffmpeg's fixed %05d pattern needs to match it exactly.
scene.render.filepath = FRAMES_DIR + "/frame_#####"

print("Rendering image sequence…")
bpy.ops.render.render(animation=True)
print("RENDER_COMPLETE")

print("Mixing down audio…")
bpy.ops.sound.mixdown(filepath=WAV_PATH, container='WAV', codec='PCM', format='S16')
print("MIXDOWN_COMPLETE")

print(f"FRAME_START={{scene.frame_start}}")
print(f"FRAME_END={{scene.frame_end}}")
print(f"FPS={{fps!r}}")
print(f"FPS_NUM={{scene.render.fps}}")
print(f"FPS_BASE={{scene.render.fps_base!r}}")
print(f"RES_X={{out_x}}")
print(f"RES_Y={{out_y}}")
'''


def run_blender_render(blender_bin: str, blend_file: str, frames_dir: str,
                        wav_path: str, image_format: str = "PNG",
                        jpeg_quality: int = 85,
                        target_height: int = 0) -> dict | None:
    """Runs the render+mixdown in Blender. Returns parsed metadata dict, or
    None on failure."""
    script_src = RENDER_TEMPLATE.format(
        blend_file=blend_file, frames_dir=frames_dir, wav_path=wav_path,
        image_format=image_format, jpeg_quality=jpeg_quality,
        target_height=target_height,
    )

    tmp_fd, tmp_path = tempfile.mkstemp(suffix=".py", prefix="render_export_")
    try:
        with os.fdopen(tmp_fd, "w") as f:
            f.write(script_src)

        say("Opening Blender…")
        print()

        meta = {}
        render_done = False
        mixdown_done = False
        proc = subprocess.Popen(
            [blender_bin, "--background", "--python", tmp_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        for line in proc.stdout:
            line = line.rstrip()
            if line:
                print(f"  blender | {line}")
            if line == "RENDER_COMPLETE":
                render_done = True
            elif line == "MIXDOWN_COMPLETE":
                mixdown_done = True
            elif line.startswith("FRAME_START="):
                meta["frame_start"] = int(line.split("=", 1)[1])
            elif line.startswith("FRAME_END="):
                meta["frame_end"] = int(line.split("=", 1)[1])
            elif line.startswith("FPS="):
                meta["fps"] = float(line.split("=", 1)[1])
            elif line.startswith("FPS_NUM="):
                meta["fps_num"] = int(line.split("=", 1)[1])
            elif line.startswith("FPS_BASE="):
                meta["fps_base"] = float(line.split("=", 1)[1])
            elif line.startswith("RES_X="):
                meta["res_x"] = int(line.split("=", 1)[1])
            elif line.startswith("RES_Y="):
                meta["res_y"] = int(line.split("=", 1)[1])
        proc.wait()
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    if proc.returncode != 0 or not render_done or not mixdown_done:
        return None
    return meta


# ---------------------------------------------------------------------------
# ffmpeg mux
# ---------------------------------------------------------------------------

def mux_final_mp4(ffmpeg_bin: str, frames_dir: str, wav_path: str, meta: dict,
                   out_path: str, crf: int, preset: str, handoff: bool,
                   dry_run: bool, frame_ext: str = "png", gop: int | None = None,
                   audio_bitrate: str = "192k") -> bool:
    cmd = [
        ffmpeg_bin, "-y",
        "-framerate", f"{meta['fps']:.6f}",
        "-start_number", str(meta["frame_start"]),
        "-i", os.path.join(frames_dir, f"frame_%05d.{frame_ext}"),
        "-i", wav_path,
        "-c:v", "libx264",
        "-crf", str(crf),
        "-preset", preset,
    ]
    if handoff:
        cmd += ["-g", "1"]
    elif gop:
        cmd += ["-g", str(gop)]
    cmd += [
        # yuv420p needs even dimensions on both axes. A scaled review render
        # can land on an odd number (2160 * 22% = 475), which fails the mux
        # outright — round down to even rather than reject the render.
        "-vf", "scale=trunc(iw/2)*2:trunc(ih/2)*2",
        "-pix_fmt", "yuv420p",
        "-c:a", "aac",
        "-b:a", audio_bitrate,
        "-shortest",
        out_path,
    ]

    if dry_run:
        say(f"[dry-run] would run: {' '.join(cmd)}")
        return True

    say("Muxing final MP4 with ffmpeg…")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        warn("ffmpeg failed:")
        print(result.stderr[-4000:], file=sys.stderr)
        return False
    return True


# ---------------------------------------------------------------------------
# Review sidecar
# ---------------------------------------------------------------------------

def write_review_sidecar(out_path: str, blend_file: str, meta: dict) -> str:
    """Writes the JSON that lets cuts turn a position in the proxy back into a
    Blender scene frame.

    Deliberately a separate file rather than tags inside the MP4: the proxy
    stays an ordinary video anything can play, the mapping stays readable and
    hand-editable, and cuts can parse it with json_decode instead of shelling
    out to ffprobe on every page load. The two are matched by filename.
    """
    # Blender stores fps as an int plus a float fps_base (30 / 1.001), which is
    # 29.97 the same way a float never quite is. Recover the exact rational so
    # the frame math can't drift over a long timeline.
    base = Fraction(meta["fps_base"]).limit_denominator(100000)
    rational = Fraction(meta["fps_num"]) / base
    duration_frames = meta["frame_end"] - meta["frame_start"] + 1

    data = {
        "schema": "vip-review/1",
        "generated": datetime.datetime.now().astimezone().isoformat(timespec="seconds"),
        "blend": os.path.basename(blend_file),
        "blend_path": blend_file,
        "proxy": os.path.basename(out_path),
        "frame_start": meta["frame_start"],
        "frame_end": meta["frame_end"],
        "duration_frames": duration_frames,
        "duration_seconds": round(duration_frames * rational.denominator
                                   / rational.numerator, 3),
        "fps": meta["fps"],
        "fps_num": rational.numerator,
        "fps_den": rational.denominator,
        "width": meta.get("res_x"),
        "height": meta.get("res_y"),
        "note": "frame = round(seconds * fps_num / fps_den) + frame_start",
    }

    json_path = os.path.splitext(out_path)[0] + ".json"
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)
        f.write("\n")
    return json_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Render a Blender VSE project to a final MP4 via a PNG "
                     "sequence + ffmpeg mux (not Blender's built-in encoder)."
    )
    parser.add_argument("blend_file", nargs="?", default=None,
                         help="Path to the .blend to render. Prompted if omitted.")
    parser.add_argument("--output", "-o", default=None,
                         help="Output MP4 path (default: sibling <blend_stem>.mp4)")
    parser.add_argument("--crf", type=int, default=None,
                         help="x264 CRF (default: 18, matching 2-transcode.py; "
                              "28 under --review)")
    parser.add_argument("--preset", default=None,
                         help="x264 preset (default: slow; veryfast under --review)")
    parser.add_argument("--review", action="store_true",
                         help="Render a small, phone-friendly review proxy of the "
                              "whole timeline instead of a delivery copy, plus a "
                              "JSON sidecar mapping video time back to scene "
                              "frames. Feeds the marker round in cuts.")
    parser.add_argument("--review-height", type=int, default=480,
                         help="Target height for --review (default: 480). Aspect "
                              "ratio and composition are preserved.")
    parser.add_argument("--review-quality", type=int, default=85,
                         help="JPEG quality for --review intermediate frames "
                              "(default: 85)")
    parser.add_argument("--handoff", action="store_true",
                         help="Keyframe interval 1 (-g 1) for scrub-friendly "
                              "handoff to captions/AE/Premiere — not for a "
                              "final delivery copy, it bloats file size.")
    parser.add_argument("--keep-frames", action="store_true",
                         help="Don't delete the temp PNG sequence after muxing "
                              "(useful for debugging a bad render).")
    parser.add_argument("--blender", default=None,
                         help="Path to the Blender executable (auto-detected if omitted)")
    parser.add_argument("--dry-run", action="store_true",
                         help="Show what would run without rendering anything")
    args = parser.parse_args()

    # ── Resolve .blend path ──────────────────────────────────────────────────
    if args.blend_file:
        blend_file = sanitize_path(args.blend_file)
    else:
        blend_file = prompt_for_blend()

    blend_file = os.path.abspath(os.path.expanduser(blend_file))

    if not os.path.isfile(blend_file):
        die(f"File not found: {blend_file}")
    if not blend_file.endswith(".blend"):
        die(f"Not a .blend file: {blend_file}")

    # --review is a preset, not a separate pipeline step: same render path,
    # different dials. Explicit --crf / --preset still win over the preset.
    crf = args.crf if args.crf is not None else (28 if args.review else 18)
    preset = args.preset or ("veryfast" if args.review else "slow")
    image_format = "JPEG" if args.review else "PNG"
    frame_ext = "jpg" if args.review else "png"
    target_height = args.review_height if args.review else 0
    gop = 30 if args.review else None
    audio_bitrate = "96k" if args.review else "192k"
    suffix = "_review.mp4" if args.review else ".mp4"

    out_path = args.output or (os.path.splitext(blend_file)[0] + suffix)
    out_path = os.path.abspath(os.path.expanduser(out_path))

    # ── Find tools ────────────────────────────────────────────────────────────
    header("Step 1: Finding tools")
    blender_bin = args.blender or find_blender()
    ffmpeg_bin = find_tool("ffmpeg", ["/opt/homebrew/bin/ffmpeg", "/usr/bin/ffmpeg"])
    ok(f"Found ffmpeg: {ffmpeg_bin}")

    if args.dry_run:
        say(f"\n[dry-run] would render: {blend_file}")
        say(f"[dry-run] would write : {out_path}")
        sys.exit(0)

    # ── Render PNG sequence + audio mixdown ──────────────────────────────────
    header("Step 2: Rendering in Blender")
    frames_dir = tempfile.mkdtemp(prefix="render_export_frames_")
    wav_fd, wav_path = tempfile.mkstemp(suffix=".wav", prefix="render_export_audio_")
    os.close(wav_fd)

    try:
        meta = run_blender_render(
            blender_bin, blend_file, frames_dir, wav_path,
            image_format=image_format, jpeg_quality=args.review_quality,
            target_height=target_height,
        )
        if not meta:
            die("Blender render/mixdown did not complete successfully.")

        # ── Mux ───────────────────────────────────────────────────────────────
        header("Step 3: Muxing final MP4")
        success = mux_final_mp4(
            ffmpeg_bin, frames_dir, wav_path, meta, out_path,
            crf, preset, args.handoff, args.dry_run,
            frame_ext=frame_ext, gop=gop, audio_bitrate=audio_bitrate,
        )
        if not success:
            die("ffmpeg mux failed.")
    finally:
        try:
            os.unlink(wav_path)
        except OSError:
            pass
        if not args.keep_frames:
            shutil.rmtree(frames_dir, ignore_errors=True)
        else:
            say(f"\nKept {image_format} sequence at: {frames_dir}")

    header("Done")
    ok(f"Exported: {out_path}\n")

    if args.review:
        json_path = write_review_sidecar(out_path, blend_file, meta)
        ok(f"Frame map: {json_path}\n")
        size_mb = os.path.getsize(out_path) / (1024 * 1024)
        say(f"Proxy size: {size_mb:.0f} MB "
            f"({meta.get('res_x')}x{meta.get('res_y')})")
        print()
        say("Next step — copy BOTH files to the cuts host, then mark them up:")
        print(f"  scp \"{out_path}\" \"{json_path}\" evan@mac-minty:~/www/cuts/review/")
        print("  → open cuts on your phone, place the F / u pairs, export the markers")
        print(f"  → python3 mobile-markers/import-markers.py")
        print()
    else:
        say("Next step:")
        print(f"  python3 captions/captions.py \"{out_path}\"")
        print(f"  python3 after-effects/export-to-ae.py \"{blend_file}\"")
        print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print()
        die("Interrupted by user (Ctrl-C).")
    except EOFError:
        print()
        die("No input available (stdin closed). Pass the path as an argument instead.")
