#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
render-export.py — Render a Blender VSE project to a final MP4

Renders outside Blender's built-in FFmpeg encoder, which doesn't expose real
CRF/GOP/preset control. Instead: render a lossless, resumable PNG image
sequence via Blender's Python API, mix the VSE's audio down to WAV, then
shell out to ffmpeg to mux the two into the final MP4 with real encoder
control — matching the CRF 18 standard transcode.py already holds the rest
of the pipeline to.

Usage:
    python3 render-export.py /path/to/project.blend
    python3 render-export.py                          # prompted to drag-and-drop
    python3 render-export.py project.blend --handoff   # keyframe interval 1,
                                                         # for captions/AE/Premiere
    python3 render-export.py project.blend --dry-run

Dependencies:
    blender — must be on PATH or at the macOS default location
    ffmpeg  — must be on PATH

Platform: macOS primary, Linux Mint compatible.
"""

import argparse
import os
import shutil
import subprocess
import sys
import tempfile

# ---------------------------------------------------------------------------
# ANSI color helpers
# ---------------------------------------------------------------------------

USE_COLOR = sys.stdout.isatty()

def _c(code, text):
    return f"\033[{code}m{text}\033[0m" if USE_COLOR else text

def ok(msg):     print(_c("0;32",  f"✔ {msg}"))
def warn(msg):   print(_c("1;33",  f"⚠ {msg}"), file=sys.stderr)
def die(msg):    print(_c("0;31",  f"✖ {msg}"), file=sys.stderr); sys.exit(1)
def say(msg):    print(_c("0;36",  msg))
def header(msg): print(_c("1;36",  f"\n── {msg} ──\n"))


# ---------------------------------------------------------------------------
# Path sanitiser (drag-and-drop / copy-paste safe)
# ---------------------------------------------------------------------------

def sanitize_path(raw: str) -> str:
    p = raw.strip()
    if len(p) >= 2 and p[0] in ('"', "'") and p[-1] == p[0]:
        p = p[1:-1]
    for esc in (" ", "&", "(", ")", "[", "]", "!", "#", "$", "@", ",", ";"):
        p = p.replace(f"\\{esc}", esc)
    return p.strip()


def prompt_for_blend() -> str:
    print()
    print("  Drag-and-drop your .blend file here, or paste/type the path:")
    print("  > ", end="", flush=True)
    return sanitize_path(input())


# ---------------------------------------------------------------------------
# Tool discovery
# ---------------------------------------------------------------------------

BLENDER_HINTS = [
    "/Applications/Blender.app/Contents/MacOS/Blender",
    "/usr/bin/blender",
    "/usr/local/bin/blender",
    os.path.expanduser("~/blender/blender"),
]

def find_blender() -> str:
    found = shutil.which("blender")
    if not found:
        for h in BLENDER_HINTS:
            if h and os.path.isfile(h) and os.access(h, os.X_OK):
                found = h
                break
    if not found:
        die(
            "blender not found on PATH or at common locations.\n"
            "  Install Blender or add it to PATH and try again."
        )
    ok(f"Found blender: {found}")
    return found


def find_tool(name: str, hints: list[str] | None = None) -> str:
    found = shutil.which(name)
    if not found and hints:
        for h in hints:
            if h and os.path.isfile(h) and os.access(h, os.X_OK):
                found = h
                break
    if not found:
        die(f"'{name}' not found. Install it or add it to PATH.\n"
            f"  macOS:  brew install ffmpeg")
    return found


# ---------------------------------------------------------------------------
# Blender Python payload — PNG sequence render + audio mixdown
# ---------------------------------------------------------------------------

RENDER_TEMPLATE = '''\
# AUTO-GENERATED by render-export.py — do not edit by hand
import bpy

BLEND_FILE = {blend_file!r}
FRAMES_DIR = {frames_dir!r}
WAV_PATH   = {wav_path!r}

bpy.ops.wm.open_mainfile(filepath=BLEND_FILE)

scene = bpy.context.scene
fps = scene.render.fps / scene.render.fps_base

print()
print("=" * 60)
print("  RENDER EXPORT")
print("=" * 60)
print(f"  Input       : {{BLEND_FILE}}")
print(f"  Frame range : {{scene.frame_start}} - {{scene.frame_end}}")
print(f"  FPS         : {{fps:.6f}}")
print(f"  Resolution  : {{scene.render.resolution_x}}x{{scene.render.resolution_y}}")
print("=" * 60)

# ── PNG image sequence — lossless, resumable, real encoder control happens
# later in ffmpeg rather than Blender's own limited FFmpeg output panel.
scene.render.image_settings.file_format = 'PNG'
scene.render.image_settings.color_mode = 'RGB'
scene.render.image_settings.color_depth = '8'
scene.render.use_file_extension = True
# Explicit 5-digit '#' padding — Blender's default padding width varies with
# frame count, and ffmpeg's fixed %05d pattern needs to match it exactly.
scene.render.filepath = FRAMES_DIR + "/frame_#####"

print("Rendering PNG sequence…")
bpy.ops.render.render(animation=True)
print("RENDER_COMPLETE")

print("Mixing down audio…")
bpy.ops.sound.mixdown(filepath=WAV_PATH, container='WAV', codec='PCM', format='S16')
print("MIXDOWN_COMPLETE")

print(f"FRAME_START={{scene.frame_start}}")
print(f"FRAME_END={{scene.frame_end}}")
print(f"FPS={{fps!r}}")
'''


def run_blender_render(blender_bin: str, blend_file: str, frames_dir: str, wav_path: str) -> dict | None:
    """Runs the render+mixdown in Blender. Returns parsed metadata dict, or
    None on failure."""
    script_src = RENDER_TEMPLATE.format(
        blend_file=blend_file, frames_dir=frames_dir, wav_path=wav_path,
    )

    tmp_fd, tmp_path = tempfile.mkstemp(suffix=".py", prefix="render_export_")
    try:
        with os.fdopen(tmp_fd, "w") as f:
            f.write(script_src)

        say("Opening Blender…")
        print()

        meta = {}
        render_done = False
        mixdown_done = False
        proc = subprocess.Popen(
            [blender_bin, "--background", "--python", tmp_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        for line in proc.stdout:
            line = line.rstrip()
            if line:
                print(f"  blender | {line}")
            if line == "RENDER_COMPLETE":
                render_done = True
            elif line == "MIXDOWN_COMPLETE":
                mixdown_done = True
            elif line.startswith("FRAME_START="):
                meta["frame_start"] = int(line.split("=", 1)[1])
            elif line.startswith("FRAME_END="):
                meta["frame_end"] = int(line.split("=", 1)[1])
            elif line.startswith("FPS="):
                meta["fps"] = float(line.split("=", 1)[1])
        proc.wait()
    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    if proc.returncode != 0 or not render_done or not mixdown_done:
        return None
    return meta


# ---------------------------------------------------------------------------
# ffmpeg mux
# ---------------------------------------------------------------------------

def mux_final_mp4(ffmpeg_bin: str, frames_dir: str, wav_path: str, meta: dict,
                   out_path: str, crf: int, preset: str, handoff: bool,
                   dry_run: bool) -> bool:
    cmd = [
        ffmpeg_bin, "-y",
        "-framerate", f"{meta['fps']:.6f}",
        "-start_number", str(meta["frame_start"]),
        "-i", os.path.join(frames_dir, "frame_%05d.png"),
        "-i", wav_path,
        "-c:v", "libx264",
        "-crf", str(crf),
        "-preset", preset,
    ]
    if handoff:
        cmd += ["-g", "1"]
    cmd += [
        "-pix_fmt", "yuv420p",
        "-c:a", "aac",
        "-b:a", "192k",
        "-shortest",
        out_path,
    ]

    if dry_run:
        say(f"[dry-run] would run: {' '.join(cmd)}")
        return True

    say("Muxing final MP4 with ffmpeg…")
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        warn("ffmpeg failed:")
        print(result.stderr[-4000:], file=sys.stderr)
        return False
    return True


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Render a Blender VSE project to a final MP4 via a PNG "
                     "sequence + ffmpeg mux (not Blender's built-in encoder)."
    )
    parser.add_argument("blend_file", nargs="?", default=None,
                         help="Path to the .blend to render. Prompted if omitted.")
    parser.add_argument("--output", "-o", default=None,
                         help="Output MP4 path (default: sibling <blend_stem>.mp4)")
    parser.add_argument("--crf", type=int, default=18,
                         help="x264 CRF (default: 18, matching transcode.py)")
    parser.add_argument("--preset", default="slow",
                         help="x264 preset (default: slow)")
    parser.add_argument("--handoff", action="store_true",
                         help="Keyframe interval 1 (-g 1) for scrub-friendly "
                              "handoff to captions/AE/Premiere — not for a "
                              "final delivery copy, it bloats file size.")
    parser.add_argument("--keep-frames", action="store_true",
                         help="Don't delete the temp PNG sequence after muxing "
                              "(useful for debugging a bad render).")
    parser.add_argument("--blender", default=None,
                         help="Path to the Blender executable (auto-detected if omitted)")
    parser.add_argument("--dry-run", action="store_true",
                         help="Show what would run without rendering anything")
    args = parser.parse_args()

    # ── Resolve .blend path ──────────────────────────────────────────────────
    if args.blend_file:
        blend_file = sanitize_path(args.blend_file)
    else:
        blend_file = prompt_for_blend()

    blend_file = os.path.abspath(os.path.expanduser(blend_file))

    if not os.path.isfile(blend_file):
        die(f"File not found: {blend_file}")
    if not blend_file.endswith(".blend"):
        die(f"Not a .blend file: {blend_file}")

    out_path = args.output or (os.path.splitext(blend_file)[0] + ".mp4")
    out_path = os.path.abspath(os.path.expanduser(out_path))

    # ── Find tools ────────────────────────────────────────────────────────────
    header("Step 1: Finding tools")
    blender_bin = args.blender or find_blender()
    ffmpeg_bin = find_tool("ffmpeg", ["/opt/homebrew/bin/ffmpeg", "/usr/bin/ffmpeg"])
    ok(f"Found ffmpeg: {ffmpeg_bin}")

    if args.dry_run:
        say(f"\n[dry-run] would render: {blend_file}")
        say(f"[dry-run] would write : {out_path}")
        sys.exit(0)

    # ── Render PNG sequence + audio mixdown ──────────────────────────────────
    header("Step 2: Rendering in Blender")
    frames_dir = tempfile.mkdtemp(prefix="render_export_frames_")
    wav_fd, wav_path = tempfile.mkstemp(suffix=".wav", prefix="render_export_audio_")
    os.close(wav_fd)

    try:
        meta = run_blender_render(blender_bin, blend_file, frames_dir, wav_path)
        if not meta:
            die("Blender render/mixdown did not complete successfully.")

        # ── Mux ───────────────────────────────────────────────────────────────
        header("Step 3: Muxing final MP4")
        success = mux_final_mp4(
            ffmpeg_bin, frames_dir, wav_path, meta, out_path,
            args.crf, args.preset, args.handoff, args.dry_run,
        )
        if not success:
            die("ffmpeg mux failed.")
    finally:
        try:
            os.unlink(wav_path)
        except OSError:
            pass
        if not args.keep_frames:
            shutil.rmtree(frames_dir, ignore_errors=True)
        else:
            say(f"\nKept PNG sequence at: {frames_dir}")

    header("Done")
    ok(f"Exported: {out_path}\n")
    say("Next step:")
    print(f"  python3 captions/captions.py \"{out_path}\"")
    print(f"  python3 after-effects/export-to-ae.py \"{blend_file}\"")
    print()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print()
        die("Interrupted by user (Ctrl-C).")
