#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
vse-remove-markers.py — Remove all timeline markers from a Blender VSE project

Opens a .blend file, removes every timeline marker, and saves in place.

Usage:
    python3 vse-remove-markers.py /path/to/project.blend
    python3 vse-remove-markers.py          # prompted to drag-and-drop

Dependencies:
    blender — must be on PATH or at the macOS default location

Platform: macOS primary, Linux Mint compatible.
"""

import os
import subprocess
import sys
import tempfile

# ---------------------------------------------------------------------------
# ANSI color helpers
# ---------------------------------------------------------------------------

USE_COLOR = sys.stdout.isatty()

def _c(code, text):
    return f"\033[{code}m{text}\033[0m" if USE_COLOR else text

def ok(msg):     print(_c("0;32",  f"✔ {msg}"))
def warn(msg):   print(_c("1;33",  f"⚠ {msg}"), file=sys.stderr)
def die(msg):    print(_c("0;31",  f"✖ {msg}"), file=sys.stderr); sys.exit(1)
def say(msg):    print(_c("0;36",  msg))


# ---------------------------------------------------------------------------
# Path sanitiser (drag-and-drop / copy-paste safe)
# ---------------------------------------------------------------------------

def sanitize_path(raw: str) -> str:
    p = raw.strip()
    if len(p) >= 2 and p[0] in ('"', "'") and p[-1] == p[0]:
        p = p[1:-1]
    for esc in (" ", "&", "(", ")", "[", "]", "!", "#", "$", "@", ",", ";"):
        p = p.replace(f"\\{esc}", esc)
    return p.strip()


def prompt_for_blend() -> str:
    print()
    print("  Drag-and-drop your .blend file here, or paste/type the path:")
    print("  > ", end="", flush=True)
    return sanitize_path(input())


# ---------------------------------------------------------------------------
# Tool discovery
# ---------------------------------------------------------------------------

BLENDER_HINTS = [
    "/Applications/Blender.app/Contents/MacOS/Blender",
    "/usr/bin/blender",
    "/usr/local/bin/blender",
    os.path.expanduser("~/blender/blender"),
]

def find_blender() -> str:
    import shutil
    found = shutil.which("blender")
    if not found:
        for h in BLENDER_HINTS:
            if h and os.path.isfile(h) and os.access(h, os.X_OK):
                found = h
                break
    if not found:
        die(
            "blender not found on PATH or at common locations.\n"
            "  Install Blender or add it to PATH and try again."
        )
    ok(f"Found blender: {found}")
    return found


# ---------------------------------------------------------------------------
# Blender Python payload
# ---------------------------------------------------------------------------

REMOVE_TEMPLATE = '''\
# AUTO-GENERATED by vse-remove-markers.py — do not edit by hand
import bpy
import sys

BLEND_FILE = {blend_file!r}

bpy.ops.wm.open_mainfile(filepath=BLEND_FILE)

scene  = bpy.context.scene
count  = len(scene.timeline_markers)

print()
print("=" * 60)
print("  VSE REMOVE MARKERS")
print("=" * 60)
print(f"  File   : {{BLEND_FILE}}")
print(f"  Markers: {{count}}")
print("=" * 60)

if count == 0:
    print("  Nothing to remove.")
else:
    while scene.timeline_markers:
        scene.timeline_markers.remove(scene.timeline_markers[0])
    print(f"  Removed {{count}} marker(s).")

bpy.ops.wm.save_mainfile()
print(f"  Saved: {{BLEND_FILE}}")
print("REMOVE_COMPLETE")
'''


# ---------------------------------------------------------------------------
# Run Blender headlessly
# ---------------------------------------------------------------------------

def run_blender(blender_bin: str, blend_file: str) -> bool:
    script_src = REMOVE_TEMPLATE.format(blend_file=blend_file)

    tmp_fd, tmp_path = tempfile.mkstemp(suffix=".py", prefix="vse_remove_markers_")
    try:
        with os.fdopen(tmp_fd, "w") as f:
            f.write(script_src)

        say("Opening Blender…")
        print()

        success = False
        proc = subprocess.Popen(
            [blender_bin, "--background", "--python", tmp_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        for line in proc.stdout:
            line = line.rstrip()
            if line:
                print(f"  {line}")
            if "REMOVE_COMPLETE" in line:
                success = True
        proc.wait()

    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    if proc.returncode != 0:
        return False
    return success


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    # ── Resolve .blend path ──────────────────────────────────────────────────
    if len(sys.argv) > 1:
        blend_file = sanitize_path(sys.argv[1])
    else:
        blend_file = prompt_for_blend()

    blend_file = os.path.abspath(os.path.expanduser(blend_file))

    if not os.path.isfile(blend_file):
        die(f"File not found: {blend_file}")
    if not blend_file.endswith(".blend"):
        die(f"Not a .blend file: {blend_file}")

    # ── Find Blender ─────────────────────────────────────────────────────────
    blender_bin = find_blender()

    # ── Run ──────────────────────────────────────────────────────────────────
    success = run_blender(blender_bin, blend_file)

    if not success:
        sys.exit(1)


if __name__ == "__main__":
    main()
