#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
vse-validate-markers.py — Marker validation step of the Video Intake & Blender VSE Pipeline

Reads timeline markers from a Blender .blend file, validates F/u pairs,
checks for overlapping ranges, saves a *_cut.blend copy, and prints the
loop count for the Keyboard Maestro macro.

Markers must be placed in pairs:
    Start: name begins with "F"  (e.g. F1, F2 …)
    End:   name is exactly "u"

Usage:
    python3 vse-validate-markers.py /path/to/project.blend
    python3 vse-validate-markers.py          # prompted to drag-and-drop

Dependencies:
    blender — must be on PATH or at the macOS default location

Platform: macOS primary, Linux Mint compatible.
"""

import os
import re
import subprocess
import sys
import tempfile

# ---------------------------------------------------------------------------
# ANSI color helpers
# ---------------------------------------------------------------------------

USE_COLOR = sys.stdout.isatty()

def _c(code, text):
    return f"\033[{code}m{text}\033[0m" if USE_COLOR else text

def say(msg):    print(_c("0;36",  msg))
def ok(msg):     print(_c("0;32",  f"✔ {msg}"))
def warn(msg):   print(_c("1;33",  f"⚠ {msg}"), file=sys.stderr)
def die(msg):    print(_c("0;31",  f"✖ {msg}"), file=sys.stderr); sys.exit(1)
def header(msg): print(_c("1;36",  f"\n── {msg} ──\n"))


# ---------------------------------------------------------------------------
# Path sanitiser (drag-and-drop / copy-paste safe)
# ---------------------------------------------------------------------------

def sanitize_path(raw: str) -> str:
    p = raw.strip()
    if len(p) >= 2 and p[0] in ('"', "'") and p[-1] == p[0]:
        p = p[1:-1]
    for esc in (" ", "&", "(", ")", "[", "]", "!", "#", "$", "@", ",", ";"):
        p = p.replace(f"\\{esc}", esc)
    return p.strip()


def prompt_for_blend() -> str:
    print()
    print("  Drag-and-drop your .blend file here, or paste/type the path:")
    print("  > ", end="", flush=True)
    return sanitize_path(input())


# ---------------------------------------------------------------------------
# Tool discovery
# ---------------------------------------------------------------------------

BLENDER_HINTS = [
    "/Applications/Blender.app/Contents/MacOS/Blender",
    "/usr/bin/blender",
    "/usr/local/bin/blender",
    os.path.expanduser("~/blender/blender"),
]

def find_blender() -> str:
    import shutil
    found = shutil.which("blender")
    if not found:
        for h in BLENDER_HINTS:
            if h and os.path.isfile(h) and os.access(h, os.X_OK):
                found = h
                break
    if not found:
        die(
            "blender not found on PATH or at common locations.\n"
            "  Install Blender or add it to PATH and try again."
        )
    ok(f"Found blender: {found}")
    return found


# ---------------------------------------------------------------------------
# Blender Python payload
# ---------------------------------------------------------------------------

VALIDATE_TEMPLATE = '''\
# AUTO-GENERATED by vse-validate-markers.py — do not edit by hand
import bpy
import os
import sys

BLEND_FILE = {blend_file!r}

# ── Color helpers (stdout only; blender --background is not a tty) ────────
def ok(msg):   print(f"OK   {{msg}}")
def warn(msg): print(f"WARN {{msg}}")
def err(msg):  print(f"ERR  {{msg}}")

# ── Open file ─────────────────────────────────────────────────────────────
bpy.ops.wm.open_mainfile(filepath=BLEND_FILE)

scene   = bpy.context.scene
markers = sorted(scene.timeline_markers, key=lambda m: m.frame)
total   = len(markers)
errors  = []

print()
print("=" * 60)
print("  VSE MARKER VALIDATION")
print("=" * 60)
print(f"  File: {{BLEND_FILE}}")
print("=" * 60)

# ── List markers ──────────────────────────────────────────────────────────
print("\\n── Timeline Markers ──\\n")
if not markers:
    errors.append("No markers found in this file.")
else:
    for m in markers:
        print(f"  Frame {{m.frame:>6}}  {{m.name}}")
    print(f"\\n  Total: {{total}}")

# ── Odd count ─────────────────────────────────────────────────────────────
if markers and total % 2 != 0:
    errors.append(
        f"Odd number of markers ({{total}}). "
        "Every keep-range needs both a start (F...) and end (u) marker."
    )

# ── Pair naming check ─────────────────────────────────────────────────────
valid_pairs = []
if not errors:
    print("\\n── F / u Pair Check ──\\n")
    for i in range(0, total, 2):
        start    = markers[i]
        end      = markers[i + 1]
        pair_num = i // 2 + 1
        name_ok  = start.name.startswith("F") and end.name == "u"
        if not name_ok:
            msg = (
                f"Pair {{pair_num}} mismatch: "
                f"'{{start.name}}' @ frame {{start.frame}}  ->  "
                f"'{{end.name}}' @ frame {{end.frame}}  "
                f"(expected F... then u)"
            )
            warn(msg)
            errors.append(msg)
        else:
            print(f"  Pair {{pair_num}} OK: {{start.name}} @ {{start.frame}}  ->  u @ {{end.frame}}")
            valid_pairs.append((start.frame, end.frame))

# ── Overlap check ─────────────────────────────────────────────────────────
    print("\\n── Overlap Check ──\\n")
    overlap_found = False
    for i in range(len(valid_pairs)):
        for j in range(i + 1, len(valid_pairs)):
            a_start, a_end = valid_pairs[i]
            b_start, b_end = valid_pairs[j]
            if a_start < b_end and b_start < a_end:
                msg = (
                    f"Pairs {{i+1}} and {{j+1}} overlap: "
                    f"[{{a_start}}-{{a_end}}] overlaps [{{b_start}}-{{b_end}}]"
                )
                warn(msg)
                errors.append(msg)
                overlap_found = True
    if not overlap_found:
        ok("No overlapping ranges.")

# ── Valid ranges summary ──────────────────────────────────────────────────
print("\\n── Valid Clip Ranges ──\\n")
if valid_pairs:
    for idx, (s, e) in enumerate(valid_pairs, 1):
        print(f"  {{idx}}. frames {{s}} -> {{e}}")
else:
    print("  (none)")

# ── Bail if errors ────────────────────────────────────────────────────────
if errors:
    print(f"\\n{{'='*60}}")
    print(f"  {{len(errors)}} problem(s) found -- fix markers before running KM:")
    for e in errors:
        print(f"    - {{e}}")
    print(f"{{'='*60}}\\n")
    print("VALIDATION_FAILED")
    sys.exit(1)

# ── Loop count ────────────────────────────────────────────────────────────
loops = max(len(valid_pairs) - 1, 0)
print(f"\\n  Valid pairs : {{len(valid_pairs)}}")
print(f"  KM loops    : {{loops}}")

# ── Save _cut copy ────────────────────────────────────────────────────────
print("\\n── Saving _cut Copy ──\\n")
filepath = bpy.data.filepath
dir_path = os.path.dirname(filepath)
name, ext = os.path.splitext(os.path.basename(filepath))
cut_path  = os.path.join(dir_path, f"{{name}}_cut{{ext}}")
bpy.ops.wm.save_as_mainfile(filepath=cut_path)
print(f"  Saved: {{cut_path}}")

print(f"\\n{{'='*60}}")
print(f"  Ready. Run Keyboard Maestro macro and loop {{loops}} time(s).")
print(f"{{'='*60}}\\n")
print("VALIDATION_COMPLETE")
'''


# ---------------------------------------------------------------------------
# Run Blender headlessly
# ---------------------------------------------------------------------------

def run_blender(blender_bin: str, blend_file: str) -> tuple[bool, int | None, str | None]:
    """
    Run validation in Blender. Returns (success, km_loops, cut_path) — the
    loop count and _cut.blend path are parsed from the Blender script's
    stdout so main() can show a concrete next-step command.
    """
    script_src = VALIDATE_TEMPLATE.format(blend_file=blend_file)

    tmp_fd, tmp_path = tempfile.mkstemp(suffix=".py", prefix="vse_validate_")
    try:
        with os.fdopen(tmp_fd, "w") as f:
            f.write(script_src)

        say("Running validation in Blender…")
        print()

        success = False
        km_loops: int | None = None
        cut_path: str | None = None
        proc = subprocess.Popen(
            [blender_bin, "--background", "--python", tmp_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        for line in proc.stdout:
            line = line.rstrip()
            if line:
                print(f"  {line}")
            if "VALIDATION_COMPLETE" in line:
                success = True
            # Capture next-step inputs from the Blender script's own prints.
            m = re.search(r"KM loops\s*:\s*(\d+)", line)
            if m:
                km_loops = int(m.group(1))
            m = re.search(r"Saved:\s*(.+\.blend)\s*$", line)
            if m:
                cut_path = m.group(1).strip()
        proc.wait()

    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    if proc.returncode != 0:
        return False, km_loops, cut_path
    return success, km_loops, cut_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    # ── Resolve .blend path ──────────────────────────────────────────────────
    if len(sys.argv) > 1:
        blend_file = sanitize_path(sys.argv[1])
    else:
        blend_file = prompt_for_blend()

    blend_file = os.path.abspath(os.path.expanduser(blend_file))

    if not os.path.isfile(blend_file):
        die(f"File not found: {blend_file}")
    if not blend_file.endswith(".blend"):
        die(f"Not a .blend file: {blend_file}")

    # ── Find Blender ─────────────────────────────────────────────────────────
    blender_bin = find_blender()

    # ── Run ──────────────────────────────────────────────────────────────────
    success, km_loops, cut_path = run_blender(blender_bin, blend_file)

    if not success:
        sys.exit(1)

    # ── Next step ────────────────────────────────────────────────────────────
    header("Next step")
    repo_dir = os.path.dirname(os.path.abspath(__file__))
    trigger = os.path.join(repo_dir, "blender-km-macros", "scripts", "trigger.sh")
    loops_str = str(km_loops) if km_loops is not None else "<N>"
    cut_path_str = cut_path or f"{os.path.splitext(blend_file)[0]}_cut.blend"
    print(f"  1. Make sure Blender is running with {os.path.basename(cut_path_str)} open, then trigger")
    print(f"     the Keyboard Maestro cutting macro ({loops_str} loop(s)):")
    print(f"       \"{trigger}\" {loops_str}")
    print(f"  2. After the macro finishes, clean up the markers:")
    print(f"       python3 vse-remove-markers.py \"{cut_path_str}\"")
    print()


if __name__ == "__main__":
    main()
