#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
remove-markers.py — Second half of the Keyboard Maestro cutting round

Part of the optional `blender-km-macros/` add-on to the Video Intake & Blender
VSE Pipeline, not a numbered pipeline step. Run it after the cutting macro has
made the cuts.

Opens a <stem>_<N>_cut.blend, removes every timeline marker, and saves the
result as <stem>_<N+1>.blend — bumping the project number so each completed
round of cuts advances the chain. Input that isn't chain-shaped is saved in
place instead.

Usage:
    python3 blender-km-macros/remove-markers.py /path/to/project.blend
    python3 blender-km-macros/remove-markers.py    # prompted to drag-and-drop
    python3 blender-km-macros/remove-markers.py project.blend --blender /path/to/blender

Dependencies:
    blender — must be on PATH or at the macOS default location

Platform: macOS primary, Linux Mint compatible.
"""

import argparse
import os
import re
import subprocess
import sys
import tempfile

# ---------------------------------------------------------------------------
# ANSI color helpers
# ---------------------------------------------------------------------------

USE_COLOR = sys.stdout.isatty()

def _c(code, text):
    return f"\033[{code}m{text}\033[0m" if USE_COLOR else text

def ok(msg):     print(_c("0;32",  f"✔ {msg}"))
def warn(msg):   print(_c("1;33",  f"⚠ {msg}"), file=sys.stderr)
def die(msg):    print(_c("0;31",  f"✖ {msg}"), file=sys.stderr); sys.exit(1)
def say(msg):    print(_c("0;36",  msg))


# ---------------------------------------------------------------------------
# Path sanitiser (drag-and-drop / copy-paste safe)
# ---------------------------------------------------------------------------

def sanitize_path(raw: str) -> str:
    p = raw.strip()
    if len(p) >= 2 and p[0] in ('"', "'") and p[-1] == p[0]:
        p = p[1:-1]
    for esc in (" ", "&", "(", ")", "[", "]", "!", "#", "$", "@", ",", ";"):
        p = p.replace(f"\\{esc}", esc)
    return p.strip()


def prompt_for_blend() -> str:
    print()
    print("  Drag-and-drop your .blend file here, or paste/type the path:")
    print("  > ", end="", flush=True)
    return sanitize_path(input())


# ---------------------------------------------------------------------------
# Tool discovery
# ---------------------------------------------------------------------------

BLENDER_HINTS = [
    "/Applications/Blender.app/Contents/MacOS/Blender",
    "/usr/bin/blender",
    "/usr/local/bin/blender",
    os.path.expanduser("~/blender/blender"),
]

def find_blender() -> str:
    import shutil
    found = shutil.which("blender")
    if not found:
        for h in BLENDER_HINTS:
            if h and os.path.isfile(h) and os.access(h, os.X_OK):
                found = h
                break
    if not found:
        die(
            "blender not found on PATH or at common locations.\n"
            "  Install Blender or add it to PATH and try again."
        )
    ok(f"Found blender: {found}")
    return found


# ---------------------------------------------------------------------------
# Blender Python payload
# ---------------------------------------------------------------------------

REMOVE_TEMPLATE = '''\
# AUTO-GENERATED by remove-markers.py — do not edit by hand
import bpy
import sys

BLEND_FILE = {blend_file!r}
OUT_PATH   = {out_path!r}

bpy.ops.wm.open_mainfile(filepath=BLEND_FILE)

scene  = bpy.context.scene
count  = len(scene.timeline_markers)

print()
print("=" * 60)
print("  VSE REMOVE MARKERS")
print("=" * 60)
print(f"  Input  : {{BLEND_FILE}}")
print(f"  Output : {{OUT_PATH}}")
print(f"  Markers: {{count}}")
print("=" * 60)

if count == 0:
    print("  Nothing to remove.")
else:
    while scene.timeline_markers:
        scene.timeline_markers.remove(scene.timeline_markers[0])
    print(f"  Removed {{count}} marker(s).")

bpy.ops.wm.save_as_mainfile(filepath=OUT_PATH)
print(f"  Saved: {{OUT_PATH}}")
print("REMOVE_COMPLETE")
'''


# ---------------------------------------------------------------------------
# Run Blender headlessly
# ---------------------------------------------------------------------------

def next_project_path(cut_blend_path: str) -> str | None:
    """
    Compute the next-round project path from a `_cut.blend` produced by
    validate-markers.py.

    Given `…/project_N_cut.blend`, return `…/project_<N+1>.blend`,
    auto-bumping further if `_<N+1>.blend` already exists (from a
    half-completed earlier round). Returns None if the input doesn't
    match the chain shape — in that case the caller should fall back
    to an in-place save.
    """
    dirpath  = os.path.dirname(cut_blend_path)
    filename = os.path.basename(cut_blend_path)
    m = re.match(r"^(?P<stem>.+)_(?P<n>\d+)_cut\.blend$", filename)
    if not m:
        return None
    stem = m.group("stem")
    n    = int(m.group("n"))
    while True:
        n += 1
        candidate = os.path.join(dirpath, f"{stem}_{n}.blend")
        if not os.path.exists(candidate):
            return candidate


def run_blender(blender_bin: str, blend_file: str, out_path: str) -> bool:
    script_src = REMOVE_TEMPLATE.format(blend_file=blend_file, out_path=out_path)

    tmp_fd, tmp_path = tempfile.mkstemp(suffix=".py", prefix="vse_remove_markers_")
    try:
        with os.fdopen(tmp_fd, "w") as f:
            f.write(script_src)

        say("Opening Blender…")
        print()

        success = False
        proc = subprocess.Popen(
            [blender_bin, "--background", "--python", tmp_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        for line in proc.stdout:
            line = line.rstrip()
            if line:
                print(f"  {line}")
            if "REMOVE_COMPLETE" in line:
                success = True
        proc.wait()

    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    if proc.returncode != 0:
        return False
    return success


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Marker cleanup step: wipe all timeline markers and save the "
                    "next-round project (<stem>_<N>_cut.blend → <stem>_<N+1>.blend)."
    )
    parser.add_argument(
        "blend_file",
        nargs="?",
        default=None,
        help="Path to the _cut.blend to clean up. Omit to be prompted.",
    )
    parser.add_argument(
        "--blender",
        default=None,
        help="Path to the Blender executable. Auto-detected if omitted.",
    )
    args = parser.parse_args()

    # ── Resolve .blend path ──────────────────────────────────────────────────
    if args.blend_file:
        blend_file = sanitize_path(args.blend_file)
    else:
        blend_file = prompt_for_blend()

    blend_file = os.path.abspath(os.path.expanduser(blend_file))

    if not os.path.isfile(blend_file):
        die(f"File not found: {blend_file}")
    if not blend_file.endswith(".blend"):
        die(f"Not a .blend file: {blend_file}")

    # ── Find Blender ─────────────────────────────────────────────────────────
    blender_bin = args.blender or find_blender()

    # ── Compute next-round output path (or fall back to in-place save) ───────
    bumped_path = next_project_path(blend_file)
    out_path = bumped_path or blend_file

    # ── Run ──────────────────────────────────────────────────────────────────
    success = run_blender(blender_bin, blend_file, out_path)

    if not success:
        sys.exit(1)

    if bumped_path:
        # Successful round — emit the cycle's next-step hint pointing at the
        # freshly-bumped project file so the user can start another round of
        # marker placement immediately.
        km_dir = os.path.dirname(os.path.abspath(__file__))
        validator = os.path.join(km_dir, "validate-markers.py")
        renderer = os.path.join(os.path.dirname(km_dir), "4-render-export.py")
        say("\n── Round complete ──\n")
        ok(f"Next-round project: {out_path}\n")
        say("Next step — another round of cuts:")
        print(f"  1. Open the new project and place markers:")
        print(f"       open \"{out_path}\"")
        print(f"  2. When markers are in, validate them:")
        print(f"       python3 \"{validator}\" \"{out_path}\"")
        print()
        say("Or, if you're done cutting, render the final MP4:")
        print(f"  python3 \"{renderer}\" \"{out_path}\"")
        print()
    else:
        # Input wasn't a chain-shaped _cut.blend — legacy in-place behaviour.
        say("\n── Markers removed ──\n")
        ok(f"Edit-ready project: {out_path}\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print()
        die("Interrupted by user (Ctrl-C).")
    except EOFError:
        print()
        die("No input available (stdin closed). Pass the path as an argument instead.")
