#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
export-to-ae.py — export a Blender VSE timeline to JSON for After Effects

Drives Blender headlessly against your latest `<project>_<N>.blend` (the
end of your cut chain) and runs an embedded Blender Python payload that
walks every MOVIE strip on the VSE and writes a sibling JSON next to the
.blend: `<stem>_vse_export.json`. From there, AE's `import_blender.jsx`
reads the JSON and builds a matching composition.

Usage:
    python3 after-effects/export-to-ae.py /path/to/project_5.blend
    python3 after-effects/export-to-ae.py          # prompted — supports drag-and-drop

Dependencies:
    blender — already required by the main pipeline
    After Effects (any reasonably modern version) — for the import step

Platform: macOS primary, Linux Mint compatible.
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import tempfile

# ---------------------------------------------------------------------------
# ANSI color helpers
# ---------------------------------------------------------------------------

USE_COLOR = sys.stdout.isatty()

def _c(code, text):
    return f"\033[{code}m{text}\033[0m" if USE_COLOR else text

def ok(msg):     print(_c("0;32",  f"✔ {msg}"))
def warn(msg):   print(_c("1;33",  f"⚠ {msg}"), file=sys.stderr)
def die(msg):    print(_c("0;31",  f"✖ {msg}"), file=sys.stderr); sys.exit(1)
def say(msg):    print(_c("0;36",  msg))
def header(msg): print(_c("1;36",  f"\n── {msg} ──\n"))


# ---------------------------------------------------------------------------
# Path sanitiser (drag-and-drop / copy-paste safe)
# ---------------------------------------------------------------------------

def sanitize_path(raw: str) -> str:
    p = raw.strip()
    if len(p) >= 2 and p[0] in ('"', "'") and p[-1] == p[0]:
        p = p[1:-1]
    for esc in (" ", "&", "(", ")", "[", "]", "!", "#", "$", "@", ",", ";"):
        p = p.replace(f"\\{esc}", esc)
    return p.strip()


def prompt_for_blend() -> str:
    print()
    print("  Drag-and-drop your .blend file here, or paste/type the path:")
    print("  > ", end="", flush=True)
    return sanitize_path(input())


# ---------------------------------------------------------------------------
# Blender discovery
# ---------------------------------------------------------------------------

BLENDER_HINTS = [
    "/Applications/Blender.app/Contents/MacOS/Blender",
    "/usr/bin/blender",
    "/usr/local/bin/blender",
    os.path.expanduser("~/blender/blender"),
]


def find_blender(override: str | None = None) -> str:
    if override:
        if not (os.path.isfile(override) and os.access(override, os.X_OK)):
            die(f"Not executable: {override}")
        ok(f"Using Blender: {override}")
        return override

    found = shutil.which("blender")
    if not found:
        for h in BLENDER_HINTS:
            if h and os.path.isfile(h) and os.access(h, os.X_OK):
                found = h
                break
    if not found:
        die(
            "blender not found on PATH or at common locations.\n"
            "  Install Blender or pass --blender /path/to/blender."
        )
    ok(f"Found Blender: {found}")
    return found


# ---------------------------------------------------------------------------
# Blender Python payload (embedded — written to a temp file at run time and
# fed to `blender -b <blend> --python <tempfile>`, matching the pattern used
# by import-vse.py, vse-validate-markers.py, and vse-remove-markers.py).
#
# Walks the VSE timeline of whatever .blend Blender opened, writes a sibling
# JSON, and prints `WROTE: <path>` so the wrapper can pluck the path back.
# ---------------------------------------------------------------------------

EXPORT_TEMPLATE = '''\
# AUTO-GENERATED by export-to-ae.py — do not edit by hand
import bpy
import json
import os
import sys

scene  = bpy.context.scene
fps    = scene.render.fps / scene.render.fps_base
width  = scene.render.resolution_x
height = scene.render.resolution_y

if not scene.sequence_editor:
    print("ERROR: scene has no Sequence Editor — nothing to export.", file=sys.stderr)
    sys.exit(1)

blend_path = bpy.data.filepath
if not blend_path:
    print("ERROR: please save the .blend file first; export needs a directory "
          "to write the JSON into.", file=sys.stderr)
    sys.exit(1)

blend_dir  = os.path.dirname(blend_path)
blend_name = os.path.splitext(os.path.basename(blend_path))[0]
out_path   = os.path.join(blend_dir, f"{blend_name}_vse_export.json")

clips = []
max_out_sec = 0.0

for s in scene.sequence_editor.sequences_all:
    if s.type != "MOVIE":
        continue

    frame_start  = s.frame_start
    offset_start = s.frame_offset_start
    duration     = s.frame_final_duration

    timeline_start_s = (frame_start + offset_start) / fps
    in_point_s       = offset_start / fps
    out_point_s      = (offset_start + duration) / fps

    max_out_sec = max(max_out_sec, timeline_start_s + (out_point_s - in_point_s))

    clips.append({
        "name":           s.name,
        "filepath":       bpy.path.abspath(s.filepath),
        "timeline_start": round(timeline_start_s, 3),
        "in_point":       round(in_point_s, 3),
        "out_point":      round(out_point_s, 3),
        "channel":        s.channel,
        "scale_x":        getattr(s.transform, "scale_x",   1.0),
        "scale_y":        getattr(s.transform, "scale_y",   1.0),
        "translate_x":    getattr(s.transform, "offset_x",  0.0),
        "translate_y":    getattr(s.transform, "offset_y",  0.0),
    })

export = {
    "fps":           round(fps, 3),
    "comp_width":    width,
    "comp_height":   height,
    "comp_duration": round(max_out_sec, 3),
    "clips":         clips,
}

with open(out_path, "w", encoding="utf-8") as f:
    json.dump(export, f, indent=4)

print(f"✓ Exported {len(clips)} clip(s) from VSE")
print(f"WROTE: {out_path}")
'''


# ---------------------------------------------------------------------------
# Run Blender headlessly with the embedded payload
# ---------------------------------------------------------------------------

def run_export(blender_bin: str, blend_file: str) -> str:
    """
    Launch `blender -b <blend_file> --python <tempfile>`, stream output
    live, and return the JSON path the payload prints on its final
    `WROTE: <path>` line.
    """
    tmp_fd, tmp_path = tempfile.mkstemp(suffix=".py", prefix="vse_export_")
    try:
        with os.fdopen(tmp_fd, "w") as f:
            f.write(EXPORT_TEMPLATE)

        cmd = [blender_bin, "-b", blend_file, "--python", tmp_path]
        say("Running Blender headlessly…")
        print()

        json_path: str | None = None
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
        )
        for line in proc.stdout:
            line = line.rstrip()
            if line:
                print(f"  blender | {line}")
            m = re.match(r"WROTE:\s*(.+)$", line.strip())
            if m:
                json_path = m.group(1).strip()
        proc.wait()

    finally:
        try:
            os.unlink(tmp_path)
        except OSError:
            pass

    if proc.returncode != 0:
        die(f"Blender exited with code {proc.returncode}.")
    if not json_path:
        die("Blender finished but no `WROTE:` sentinel was emitted — "
            "check the script output above for an error.")
    if not os.path.isfile(json_path):
        die(f"Blender claimed to write {json_path}, but the file doesn't exist.")
    return json_path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export a Blender VSE timeline to JSON for After Effects."
    )
    parser.add_argument("blend_file", nargs="?", default=None,
                        help="The .blend to export. Omit to be prompted.")
    parser.add_argument("--blender", default=None,
                        help="Path to the Blender executable (auto-detected if omitted).")
    args = parser.parse_args()

    # ── Resolve .blend path ─────────────────────────────────────────────────
    blend_file = sanitize_path(args.blend_file) if args.blend_file else prompt_for_blend()
    blend_file = os.path.abspath(os.path.expanduser(blend_file))

    if not os.path.isfile(blend_file):
        die(f"File not found: {blend_file}")
    if not blend_file.endswith(".blend"):
        die(f"Not a .blend file: {blend_file}")

    # ── Find Blender ────────────────────────────────────────────────────────
    header("Step 1: Finding Blender")
    blender_bin = find_blender(args.blender)

    # ── Run the export payload ──────────────────────────────────────────────
    header("Step 2: Exporting VSE timeline → JSON")
    json_path = run_export(blender_bin, blend_file)

    # ── Done ────────────────────────────────────────────────────────────────
    header("Done")
    ok(f"JSON written: {json_path}\n")

    # ── Next step ───────────────────────────────────────────────────────────
    jsx_path = os.path.join(
        os.path.dirname(os.path.abspath(__file__)),
        "import_blender.jsx",
    )
    header("Next step")
    print("  1. Open After Effects.")
    print("  2. File > Scripts > Run Script File…")
    print(f"       {jsx_path}")
    print("  3. When the file picker appears, select:")
    print(f"       {json_path}")
    print()
    print("  AE will build a composition called \"Blender_VSE\" with every")
    print("  clip placed at its timeline position, scaled, and offset.")
    print()


if __name__ == "__main__":
    main()
